# Generated by Django 2.2.12 on 2020-05-26 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import twitter_parsing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100, verbose_name='хэштег')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса')),
                ('number_tweets', models.IntegerField(verbose_name='количество твитов')),
                ('result_negative', models.IntegerField(blank=True, default=twitter_parsing.models.predict, verbose_name='уровень негатива в процентах')),
                ('from_date', models.DateTimeField(verbose_name='с ')),
                ('until_date', models.DateTimeField(verbose_name='до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('text', models.TextField(verbose_name='текст')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('negative', models.BooleanField(blank=True, default=False, verbose_name='негатив')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст твита')),
                ('date', models.DateTimeField(blank=True, verbose_name='дата публикации')),
                ('negative', models.BooleanField(blank=True, verbose_name='негатив')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter_parsing.Inquiry')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации')),
                ('negative', models.IntegerField(blank=True, default=50, verbose_name='уровень негатива в процентах')),
                ('from_date', models.DateTimeField(verbose_name='с ')),
                ('until_date', models.DateTimeField(verbose_name='до')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
