# Generated by Django 3.0.7 on 2020-06-06 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_parsing', '0003_auto_20200606_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='from_date',
            field=models.DateField(verbose_name='с '),
        ),
        migrations.AlterField(
            model_name='account',
            name='until_date',
            field=models.DateField(verbose_name='до'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='from_date',
            field=models.DateField(verbose_name='с '),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='until_date',
            field=models.DateField(verbose_name='до'),
        ),
    ]
