# Generated by Django 3.0.7 on 2020-06-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_parsing', '0006_auto_20200606_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='date',
        ),
    ]
