# Generated by Django 3.0.7 on 2020-06-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_parsing', '0008_auto_20200608_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter_parsing.Account'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='inquiry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter_parsing.Inquiry'),
        ),
    ]
