# Generated by Django 3.0.7 on 2020-06-06 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_parsing', '0005_auto_20200606_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса'),
        ),
    ]
