# Generated by Django 3.0.7 on 2020-06-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_parsing', '0007_remove_tweet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='until_date',
        ),
        migrations.AddField(
            model_name='account',
            name='number_tweets',
            field=models.IntegerField(default=0, verbose_name='количество твитов'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='account',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter_parsing.Account'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='result_negative',
            field=models.IntegerField(blank=True, verbose_name='уровень негатива в процентах'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='inquiry',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter_parsing.Inquiry'),
        ),
    ]
