# Generated by Django 3.0.7 on 2020-06-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_parsing', '0009_auto_20200608_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Atweets', to='twitter_parsing.Account'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='inquiry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Itweets', to='twitter_parsing.Inquiry'),
        ),
    ]
