# Generated by Django 3.0.7 on 2020-06-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_parsing', '0010_auto_20200608_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст твита')),
                ('negative', models.BooleanField(blank=True, verbose_name='сентимент')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Atweets', to='twitter_parsing.Account')),
            ],
        ),
        migrations.CreateModel(
            name='TweetInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст твита')),
                ('negative', models.BooleanField(blank=True, verbose_name='сентимент')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Itweets', to='twitter_parsing.Inquiry')),
            ],
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
